### ISSUE TITLE
Functionality to be implemented in the wrapper

### ISSUE THREAD

**Issue by ajs97** [pclubiitk/TechTests#11]
The milestone for the Docker Output Check Wrapper mentions what must be done for a wrong answer but must it also check for Compile Errors, Segmentation Faults, TLE,etc?

**Comment by prannayk** [comment]
I am not sure by what you mean by Segmentation faults in a command? If that is the output of a compile command then in that case I guess that is it. There is not much the wrapper can do about it. It can check for non existing arguments and stuff as added functionality but I think the head developers might be able to tell us how trivial/ non-trivial that is.

**Comment by yashsriv** [comment]
As per the milestone, the wrapper should run the commands of file `arg1` - Compare the output of the last command of `arg1` with the contents of `arg2` and return 0 if they match, 1 otherwise.

While doing the above steps, it should also log all the outputs in file `arg3`.

I believe, we should just check the return codes of all commands and stop execution if they fail somewhere and log the error message if any.

**Comment by pallavagarwal07** [comment]
I thought this should be clear already. Logging means you have to log every output, including errors. The wrapper doesn't have to detect any errors, just dump any error output that is already being produced. 

Whether or not you kill the wrapper on first error is immaterial, and personally I would suggest against it (maybe a command in between needs to fail, with its return code being used in the next step)
